datasets:
  raw:
    sod:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/case_study/Spring_Oppty_Data.csv
      driver_params: {}

    spd:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/case_study/springboard_illst_prd_dat.csv
      driver_params: {}
  cleaned:
    sod:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/case_study/Spring_Oppty_Data.parquet
      driver_params: {}

    spd:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/case_study/springboard_illst_prd_dat.parquet
      driver_params: {}